
"""
全局常量配置
存放系统级、通用的固定常量，避免硬编码

职责划分：
- config.py: 应用配置（APP_TITLE、数据库连接、JWT配置等，可通过 .env 覆盖）
- constants.py: 程序固定常量（状态码、角色名称、正则表达式等）

注意：配置项不应放在此文件！
"""

# ========== 环境常量 ==========
ENV_DEVELOPMENT = "development"
ENV_TESTING = "testing"
ENV_PRODUCTION = "production"


# ========== 业务状态常量 ==========
# 用于表示启用/禁用的通用状态（Dept、Resource、DictType、DictData、TenantPlan、SystemConfig 等模型使用）
STATUS_ENABLED = 1
STATUS_DISABLED = 0

# ========== 登录日志状态常量 ==========
LOGIN_STATUS_SUCCESS = 1
LOGIN_STATUS_FAILED = 0

# ========== 租户状态常量 ==========
TENANT_STATUS_ACTIVE = "active"
TENANT_STATUS_SUSPENDED = "suspended"
TENANT_STATUS_TRIAL = "trial"
TENANT_STATUS_EXPIRED = "expired"


# ========== 资源类型常量 ==========
RESOURCE_TYPE_MENU = 1
RESOURCE_TYPE_API = 2
RESOURCE_TYPE_BUTTON = 3


# ========== 场景常量 ==========
SCENE_ADMIN = "admin"
SCENE_APP = "app"
SCENE_MERCHANT = "merchant"


# ========== 角色常量 ==========
SUPER_ADMIN_ID = 1

ROLE_PLATFORM_SUPER_ADMIN = "平台超级管理员"
ROLE_PLATFORM_OPERATOR = "平台运营管理员"
ROLE_PLATFORM_FINANCE = "平台财务管理员"
ROLE_PLATFORM_AUDITOR = "平台审核管理员"
ROLE_PLATFORM_SUPPORT = "平台运维专员"
ROLE_PLATFORM_CUSTOMER_SERVICE = "平台客服专员"
ROLE_PLATFORM_NORMAL_USER = "平台普通用户"

SYSTEM_ROLE_NAMES = [
    ROLE_PLATFORM_SUPER_ADMIN,
    ROLE_PLATFORM_OPERATOR,
    ROLE_PLATFORM_FINANCE,
    ROLE_PLATFORM_AUDITOR,
    ROLE_PLATFORM_SUPPORT,
    ROLE_PLATFORM_CUSTOMER_SERVICE,
    ROLE_PLATFORM_NORMAL_USER,
]


# ========== 正则表达式常量 ==========
PHONE_REGEX = r"^1[3-9]\d{9}$"
EMAIL_REGEX = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
ID_CARD_REGEX = r"^[1-9]\d{5}(18|19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{3}[\dXx]$"
PASSWORD_STRONG_REGEX = r"^(?=.*[a-zA-Z])(?=.*\d).{6,}$|^(?=.*[a-z])(?=.*[A-Z]).{6,}$"
USERNAME_REGEX = r"^[a-zA-Z0-9_]{4,20}$"
HOUSE_CODE_REGEX = r"^HJ\d{8}$"


# ========== 分页常量 ==========
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100


# ========== 文件扩展名常量 ==========
ALLOWED_IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "gif", "bmp", "webp"}
ALLOWED_DOC_EXTENSIONS = {"pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt"}
ALLOWED_VIDEO_EXTENSIONS = {"mp4", "avi", "mov", "wmv", "flv"}


# ========== 文件大小常量 ==========
MAX_FILE_SIZE_IMAGE = 10 * 1024 * 1024
MAX_FILE_SIZE_DOC = 50 * 1024 * 1024
MAX_FILE_SIZE_VIDEO = 500 * 1024 * 1024


# ========== 存储路径常量 ==========
STORAGE_PATH_AVATAR = "avatars"
STORAGE_PATH_HOUSE = "houses"
STORAGE_PATH_REPORT = "reports"
STORAGE_PATH_TEMP = "temp"


# ========== 房屋状态常量 ==========
HOUSE_STATUS_NORMAL = "normal"
HOUSE_STATUS_DAMAGED = "damaged"
HOUSE_STATUS_DANGEROUS = "dangerous"


# ========== 鉴定类型常量 ==========
IDENTIFICATION_TYPE_INITIAL = "initial"
IDENTIFICATION_TYPE_ROUTINE = "routine"
IDENTIFICATION_TYPE_SPECIAL = "special"


# ========== 鉴定状态常量 ==========
IDENTIFICATION_STATUS_PENDING = "pending"
IDENTIFICATION_STATUS_IN_PROGRESS = "in_progress"
IDENTIFICATION_STATUS_COMPLETED = "completed"


# ========== 编码常量 ==========
ENCODING_UTF8 = "utf-8"
ENCODING_GBK = "gbk"


# ========== 其他常量 ==========
DEFAULT_TIMEZONE = "Asia/Shanghai"
EMPTY_VALUES = (None, "", [], {}, set())


# ========== HTTP状态码常量 ==========
# 1xx 信息性状态码
HTTP_CONTINUE = 100
HTTP_SWITCHING_PROTOCOLS = 101
HTTP_PROCESSING = 102
HTTP_EARLY_HINTS = 103

# 2xx 成功状态码
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_ACCEPTED = 202
HTTP_NON_AUTHORITATIVE_INFORMATION = 203
HTTP_NO_CONTENT = 204
HTTP_RESET_CONTENT = 205
HTTP_PARTIAL_CONTENT = 206
HTTP_MULTI_STATUS = 207

# 3xx 重定向状态码
HTTP_MULTIPLE_CHOICES = 300
HTTP_MOVED_PERMANENTLY = 301
HTTP_FOUND = 302
HTTP_SEE_OTHER = 303
HTTP_NOT_MODIFIED = 304
HTTP_USE_PROXY = 305
HTTP_TEMPORARY_REDIRECT = 307
HTTP_PERMANENT_REDIRECT = 308

# 4xx 客户端错误状态码
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_PAYMENT_REQUIRED = 402
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_METHOD_NOT_ALLOWED = 405
HTTP_NOT_ACCEPTABLE = 406
HTTP_PROXY_AUTHENTICATION_REQUIRED = 407
HTTP_REQUEST_TIMEOUT = 408
HTTP_CONFLICT = 409
HTTP_GONE = 410
HTTP_LENGTH_REQUIRED = 411
HTTP_PRECONDITION_FAILED = 412
HTTP_PAYLOAD_TOO_LARGE = 413
HTTP_URI_TOO_LONG = 414
HTTP_UNSUPPORTED_MEDIA_TYPE = 415
HTTP_RANGE_NOT_SATISFIABLE = 416
HTTP_EXPECTATION_FAILED = 417
HTTP_I_AM_A_TEAPOT = 418
HTTP_MISDIRECTED_REQUEST = 421
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_LOCKED = 423
HTTP_FAILED_DEPENDENCY = 424
HTTP_TOO_EARLY = 425
HTTP_UPGRADE_REQUIRED = 426
HTTP_PRECONDITION_REQUIRED = 428
HTTP_TOO_MANY_REQUESTS = 429
HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = 451

# 5xx 服务器错误状态码
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_NOT_IMPLEMENTED = 501
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504
HTTP_VERSION_NOT_SUPPORTED = 505
HTTP_VARIANT_ALSO_NEGOTIATES = 506
HTTP_INSUFFICIENT_STORAGE = 507
HTTP_LOOP_DETECTED = 508
HTTP_NOT_EXTENDED = 510
HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511
