
"""
全局常量配置
存放系统级、通用的固定常量，避免硬编码
"""


PROJECT_NAME = "房屋鉴定管理系统"
PROJECT_VERSION = "1.0.0"
PROJECT_DESCRIPTION = "房屋鉴定业务APP + Web后端管理系统"


ENV_DEVELOPMENT = "development"
ENV_TESTING = "testing"
ENV_PRODUCTION = "production"
ENV_CHOICES = [ENV_DEVELOPMENT, ENV_TESTING, ENV_PRODUCTION]


SCENE_ADMIN = "admin"
SCENE_APP = "app"
SCENE_MERCHANT = "merchant"
SCENE_CHOICES = [SCENE_ADMIN, SCENE_APP, SCENE_MERCHANT]


RESOURCE_TYPE_MENU = 1
RESOURCE_TYPE_API = 2
RESOURCE_TYPE_BUTTON = 3
RESOURCE_TYPE_CHOICES = [RESOURCE_TYPE_MENU, RESOURCE_TYPE_API, RESOURCE_TYPE_BUTTON]


STATUS_ENABLED = 1
STATUS_DISABLED = 0
STATUS_CHOICES = [STATUS_ENABLED, STATUS_DISABLED]


SUPER_ADMIN_ID = 1


PHONE_REGEX = r"^1[3-9]\d{9}$"
EMAIL_REGEX = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
ID_CARD_REGEX = r"^[1-9]\d{5}(18|19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{3}[\dXx]$"
PASSWORD_STRONG_REGEX = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$"
USERNAME_REGEX = r"^[a-zA-Z0-9_]{4,20}$"
HOUSE_CODE_REGEX = r"^HJ\d{8}$"


DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
PAGE_SIZE_CHOICES = [10, 20, 50, 100]


ALLOWED_IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "gif", "bmp", "webp"}
ALLOWED_DOC_EXTENSIONS = {"pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt"}
ALLOWED_VIDEO_EXTENSIONS = {"mp4", "avi", "mov", "wmv", "flv"}
ALLOWED_ALL_EXTENSIONS = ALLOWED_IMAGE_EXTENSIONS | ALLOWED_DOC_EXTENSIONS | ALLOWED_VIDEO_EXTENSIONS


MAX_FILE_SIZE_IMAGE = 10 * 1024 * 1024
MAX_FILE_SIZE_DOC = 50 * 1024 * 1024
MAX_FILE_SIZE_VIDEO = 500 * 1024 * 1024


STORAGE_PATH_AVATAR = "avatars"
STORAGE_PATH_HOUSE = "houses"
STORAGE_PATH_REPORT = "reports"
STORAGE_PATH_TEMP = "temp"


JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7
JWT_TYPE_ACCESS = "access"
JWT_TYPE_REFRESH = "refresh"


HOUSE_STATUS_NORMAL = "normal"
HOUSE_STATUS_DAMAGED = "damaged"
HOUSE_STATUS_DANGEROUS = "dangerous"
HOUSE_STATUS_CHOICES = [HOUSE_STATUS_NORMAL, HOUSE_STATUS_DAMAGED, HOUSE_STATUS_DANGEROUS]


IDENTIFICATION_TYPE_INITIAL = "initial"
IDENTIFICATION_TYPE_ROUTINE = "routine"
IDENTIFICATION_TYPE_SPECIAL = "special"
IDENTIFICATION_TYPE_CHOICES = [
    IDENTIFICATION_TYPE_INITIAL,
    IDENTIFICATION_TYPE_ROUTINE,
    IDENTIFICATION_TYPE_SPECIAL,
]


IDENTIFICATION_STATUS_PENDING = "pending"
IDENTIFICATION_STATUS_IN_PROGRESS = "in_progress"
IDENTIFICATION_STATUS_COMPLETED = "completed"
IDENTIFICATION_STATUS_CHOICES = [
    IDENTIFICATION_STATUS_PENDING,
    IDENTIFICATION_STATUS_IN_PROGRESS,
    IDENTIFICATION_STATUS_COMPLETED,
]


DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"


ENCODING_UTF8 = "utf-8"
ENCODING_GBK = "gbk"


DEFAULT_TIMEZONE = "Asia/Shanghai"


EMPTY_VALUES = (None, "", [], {}, set())

